# Dataset Parameters
dataset: "MNIST"
data_path: "./data/"
use_flips: false 

# Model Parameters
# --- Use the new model name ---
model: "PoseSelective_P4CNN_MNIST"
group: "P4" 
in_channels: 1
num_classes: 10
# resnet_n and widths are no longer needed for this model

# Training Parameters
optimizer: "Adam"
learning_rate: 0.001
epochs: 200
batch_size: 128
scheduler: "StepLR"
scheduler_step_size: 40
scheduler_gamma: 0.1

# Sparsity and Temperature Schedules
sparsity_schedule:
  lambda_initial: 0.0
  lambda_final: 0.0001
  anneal_epochs: 60

temperature_schedule:
  temp_initial: 1.0
  temp_final: 0.1
  anneal_epochs: 60

# Logging Parameters
results_dir: "./results/"
