# Dataset Parameters
dataset: "MNIST"
data_path: "./data/"
use_flips: false 

# Model Parameters
model: "P4mW_ResNet44"
group: "P4" 
in_channels: 1
num_classes: 10
resnet_n: 7 
widths: [6, 13, 24] # Narrower widths for smaller datasets
ablation: "none" # "none", "no_gate", "full_equiv"

# Training Parameters
optimizer: "Adam"
learning_rate: 0.001
epochs: 100
batch_size: 128
scheduler: "StepLR"
scheduler_step_size: 30
scheduler_gamma: 0.1

# Logging Parameters
results_dir: "./results/"