# Dataset Parameters
dataset: "Rot-MNIST"
data_path: "./data/"
use_flips: false 

# Model Parameters
model: "PoseSelectiveSparse_ResNet44" # <-- IMPORTANT: Use the new model name
group: "P4" 
in_channels: 1
num_classes: 10
resnet_n: 7 
widths: [6, 13, 24]
ablation: "none"

# Training Parameters
optimizer: "Adam"
learning_rate: 0.001
epochs: 100
batch_size: 128
scheduler: "StepLR"
scheduler_step_size: 40 # Adjusted scheduler to interfere less with annealing
scheduler_gamma: 0.1

# Sparsity and Temperature Schedules (NEW)
sparsity_schedule:
  lambda_initial: 0.0
  lambda_final: 0.0001 # A common starting point, vary as per paper's sweep
  anneal_epochs: 60   # Anneal over the first 60% of epochs

temperature_schedule:
  temp_initial: 1.0
  temp_final: 0.1
  anneal_epochs: 60   # Anneal over the first 60% of epochs

# Logging Parameters
results_dir: "./results/"