# Dataset Parameters
dataset: "Rot-FashionMNIST"
data_path: "./data/"
use_flips: false
use_rotations: true

# Model Parameters
model: "PoseSelectiveSparse_ResNet44"
group: "P4" 
in_channels: 1
num_classes: 10
resnet_n: 7 
widths: [6, 13, 24] # Narrower widths for smaller datasets

# Training Parameters
optimizer: "Adam"
learning_rate: 0.001
epochs: 100
batch_size: 128
scheduler: "StepLR"
scheduler_step_size: 40
scheduler_gamma: 0.1

# Sparsity and Temperature Schedules
sparsity_schedule:
  lambda_initial: 0.0
  lambda_final: 0.0001
  anneal_epochs: 60

temperature_schedule:
  temp_initial: 1.0
  temp_final: 0.1
  anneal_epochs: 60

# Logging Parameters
results_dir: "./results/"